import angular from 'angular';

// Import our app config files
import constants  from './config/app.constants';
import appConfig  from './config/app.config';
import appRun     from './config/app.run';
import 'angular-ui-router';
// Import our templates file (generated by Gulp)
import './config/app.templates';
// Import our app functionaity
import './layout';
import './components';
import './home';
import './profile';
import './article';
import './services';
import './auth';
import './settings';
import './editor';
import './contact';
import './adventure';
import './adventure-shop';
import './restaurant';
import './restaurant-shop';
import './hotels';
import './hotel';
import './results';
import toaster from 'angularjs-toaster';

// Create and bootstrap application
const requires = [
  'ui.router',
  'templates',
  'app.layout',
  'app.components',
  'app.home',
  'app.profile',
  'app.article',
  'app.services',
  'app.auth',
  'app.settings',
  'app.editor',
  'app.contact',
  'app.adventure',
  'app.adventure-shop',
  'app.restaurant',
  'app.restaurantshop',
  'app.hotels',
  'app.hotel',
  'app.results',
  toaster
];

// Mount on window for testing
window.app = angular.module('app', requires);

angular.module('app').constant('AppConstants', constants);

angular.module('app').config(appConfig);

angular.module('app').run(appRun);

angular.bootstrap(document, ['app'], {
  strictDi: true
});
